// Generated by tools/export-catalog.mjs — do not edit by hand.
class CatalogEntry {
  const CatalogEntry({
    required this.key,
    required this.category,
    required this.slug,
    required this.name,
    required this.description,
    required this.implemented,
  });

  final String key;
  final String category;
  final String slug;
  final String name;
  final String description;
  final bool implemented;

  String get reactUrl =>
      'https://beui.dev/components/$category/${slug.contains('-') && category == 'motion' ? slug.split('-').first : slug}';
}

const catalog = <CatalogEntry>[
  CatalogEntry(key: 'agents/chat-app', category: 'agents', slug: 'chat-app', name: 'Chat App', description: '', implemented: false),
  CatalogEntry(key: 'agents/ai-sidebar', category: 'agents', slug: 'ai-sidebar', name: 'Ai Sidebar', description: '', implemented: false),
  CatalogEntry(key: 'agents/message-bubble', category: 'agents', slug: 'message-bubble', name: 'Animated Surfaces', description: 'An interactive conversation where each newly sent user row pops up once while the assistant streams into a stable row.', implemented: true),
  CatalogEntry(key: 'agents/message-bubble-avatars', category: 'agents', slug: 'message-bubble-avatars', name: 'With Avatars', description: 'Progressively arriving messages with sender avatars, metadata, delivery state, and grouped follow-up alignment.', implemented: true),
  CatalogEntry(key: 'agents/message-bubble-collapsible', category: 'agents', slug: 'message-bubble-collapsible', name: 'Show More', description: 'A long assistant message with a compact line-clamped preview and animated disclosure control.', implemented: true),
  CatalogEntry(key: 'agents/message', category: 'agents', slug: 'message', name: 'Message', description: '', implemented: true),
  CatalogEntry(key: 'agents/message-scroller', category: 'agents', slug: 'message-scroller', name: 'Message Scroller', description: '', implemented: false),
  CatalogEntry(key: 'agents/prompt-input', category: 'agents', slug: 'prompt-input', name: 'Prompt Input', description: '', implemented: true),
  CatalogEntry(key: 'agents/todo-list', category: 'agents', slug: 'todo-list', name: 'Todo List', description: '', implemented: true),
  CatalogEntry(key: 'agents/code-block', category: 'agents', slug: 'code-block', name: 'Code Block', description: '', implemented: false),
  CatalogEntry(key: 'agents/approval-card-question', category: 'agents', slug: 'approval-card-question', name: 'Questions', description: 'Guides the user through single-choice, multiple-choice, and freeform questions before returning the completed response to the agent.', implemented: false),
  CatalogEntry(key: 'agents/approval-card-review', category: 'agents', slug: 'approval-card-review', name: 'Review and Approve', description: 'Pauses an agent workflow for approval, revision, or rejection and collapses into the recorded decision.', implemented: false),
  CatalogEntry(key: 'agents/tool-result-terminal', category: 'agents', slug: 'tool-result-terminal', name: 'Terminal Output', description: 'Streams command output into a bounded viewport, follows new lines, then collapses into the completed run summary.', implemented: false),
  CatalogEntry(key: 'agents/file-diff', category: 'agents', slug: 'file-diff', name: 'File Diff', description: '', implemented: false),
  CatalogEntry(key: 'agents/tool-result-request', category: 'agents', slug: 'tool-result-request', name: 'Request Result', description: 'Presents an in-flight request and its highlighted response payload with retry and copy actions.', implemented: false),
  CatalogEntry(key: 'agents/streaming-response', category: 'agents', slug: 'streaming-response', name: 'Streaming Response', description: '', implemented: false),
  CatalogEntry(key: 'agents/image-generation', category: 'agents', slug: 'image-generation', name: 'Image Generation', description: '', implemented: false),
  CatalogEntry(key: 'agents/tool-approval', category: 'agents', slug: 'tool-approval', name: 'Tool Approval', description: '', implemented: false),
  CatalogEntry(key: 'agents/citations', category: 'agents', slug: 'citations', name: 'Citations', description: '', implemented: false),
  CatalogEntry(key: 'agents/agent-activity-text', category: 'agents', slug: 'agent-activity-text', name: 'Streaming Text', description: 'Streams freeform reasoning text into the capped viewport and keeps the completed log available behind a timed disclosure.', implemented: false),
  CatalogEntry(key: 'agents/agent-activity-steps', category: 'agents', slug: 'agent-activity-steps', name: 'Reasoning Steps', description: 'Shows completed, active, and pending reasoning steps with optional trailing metadata.', implemented: false),
  CatalogEntry(key: 'agents/agent-activity-search', category: 'agents', slug: 'agent-activity-search', name: 'Web Search', description: 'Presents a search query, progressively rendered result rows, and an overflow count.', implemented: false),
  CatalogEntry(key: 'agents/agent-activity-tools', category: 'agents', slug: 'agent-activity-tools', name: 'Tool Calls', description: 'Summarizes read, edit, and run events with monospace targets and optional line-change counts.', implemented: false),
  CatalogEntry(key: 'agents/agent-activity-mixed', category: 'agents', slug: 'agent-activity-mixed', name: 'Mixed Activity', description: 'Streams reasoning, search, and tool events in one chronological run while the viewport smoothly follows new work.', implemented: false),
  CatalogEntry(key: 'agents/agent-trace', category: 'agents', slug: 'agent-trace', name: 'Agent Trace', description: 'Streams messages and structured actions into a compact execution ledger, then summarizes the completed run by tool-call and message counts.', implemented: false),
  CatalogEntry(key: 'agents/thinking-shimmer', category: 'agents', slug: 'thinking-shimmer', name: 'Thinking Shimmer', description: 'A quiet shimmer that keeps the agent\'s current status readable while work continues.', implemented: true),
  CatalogEntry(key: 'agents/agent-progress', category: 'agents', slug: 'agent-progress', name: 'Agent Progress', description: 'A compact activity glyph, action verb, and live tabular timer for longer-running agent work.', implemented: true),
  CatalogEntry(key: 'agents/reasoning-text', category: 'agents', slug: 'reasoning-text', name: 'Reasoning Text', description: 'Shimmering reasoning copy with an ASCII loader and cascade, phrase-swap, or per-letter scramble transitions.', implemented: true),
  CatalogEntry(key: 'blocks/infinite-masonry', category: 'blocks', slug: 'infinite-masonry', name: 'Infinite Masonry', description: '', implemented: false),
  CatalogEntry(key: 'blocks/notification-stack', category: 'blocks', slug: 'notification-stack', name: 'Notification Stack', description: '', implemented: false),
  CatalogEntry(key: 'blocks/project-folder', category: 'blocks', slug: 'project-folder', name: 'Project Folder', description: '', implemented: false),
  CatalogEntry(key: 'blocks/knockout-bracket', category: 'blocks', slug: 'knockout-bracket', name: 'Knockout Bracket', description: 'Pages one round at a time. The leftmost round stacks at a fixed rhythm, each later round centers between its two feeder matches, and cards, elbow connectors, headers and stage height animate into every new layout. A third place play-off sits below the tree under its own rule. Round names, team artwork, dates and result chips all come from the data you pass.', implemented: false),
  CatalogEntry(key: 'blocks/knockout-wheel', category: 'blocks', slug: 'knockout-wheel', name: 'Knockout Wheel', description: 'The tournament drawn radially. The champion holds the hub, each round is a ring further out, and the teams themselves form the rim. Nodes spring in ring by ring, and hovering one isolates that team while the rest recede. Teams show a flag, a logo or their initials, and a deeper draw grows another ring.', implemented: false),
  CatalogEntry(key: 'blocks/dynamic-island', category: 'blocks', slug: 'dynamic-island', name: 'Dynamic Island', description: '', implemented: false),
  CatalogEntry(key: 'blocks/swap', category: 'blocks', slug: 'swap', name: 'Swap', description: '', implemented: false),
  CatalogEntry(key: 'blocks/command-palette', category: 'blocks', slug: 'command-palette', name: 'Command Palette', description: '', implemented: false),
  CatalogEntry(key: 'blocks/morphing-search', category: 'blocks', slug: 'morphing-search', name: 'Morphing Search', description: '', implemented: false),
  CatalogEntry(key: 'blocks/feedback-widget', category: 'blocks', slug: 'feedback-widget', name: 'Feedback Widget', description: '', implemented: false),
  CatalogEntry(key: 'blocks/bloom-menu', category: 'blocks', slug: 'bloom-menu', name: 'Bloom Menu', description: '', implemented: false),
  CatalogEntry(key: 'blocks/expandable-action-bar', category: 'blocks', slug: 'expandable-action-bar', name: 'Expandable Action Bar', description: '', implemented: false),
  CatalogEntry(key: 'blocks/overflow-actions', category: 'blocks', slug: 'overflow-actions', name: 'Overflow Actions', description: '', implemented: false),
  CatalogEntry(key: 'blocks/expandable-tabs', category: 'blocks', slug: 'expandable-tabs', name: 'Expandable Tabs', description: '', implemented: false),
  CatalogEntry(key: 'blocks/morphing-tabs', category: 'blocks', slug: 'morphing-tabs', name: 'Morphing Tabs', description: '', implemented: false),
  CatalogEntry(key: 'blocks/swipeable-list', category: 'blocks', slug: 'swipeable-list', name: 'Swipeable List', description: '', implemented: false),
  CatalogEntry(key: 'blocks/file-upload', category: 'blocks', slug: 'file-upload', name: 'Upload Queue', description: 'A drag-and-drop upload queue with progress rows, upload states, retry, and removal.', implemented: false),
  CatalogEntry(key: 'blocks/attachment-upload', category: 'blocks', slug: 'attachment-upload', name: 'Attachment Upload', description: 'A mixed attachment workspace with a dropzone, staggered file and image rows, animated upload, success, failure, retry and removal feedback, shared-layout image previews, and an audio waveform.', implemented: false),
  CatalogEntry(key: 'blocks/prediction-market', category: 'blocks', slug: 'prediction-market', name: 'Prediction Market', description: '', implemented: false),
  CatalogEntry(key: 'blocks/wallet-card', category: 'blocks', slug: 'wallet-card', name: 'Wallet Card', description: '', implemented: false),
  CatalogEntry(key: 'blocks/availability-scheduler', category: 'blocks', slug: 'availability-scheduler', name: 'Availability Scheduler', description: '', implemented: false),
  CatalogEntry(key: 'motion/table', category: 'motion', slug: 'table', name: 'Data Table', description: '10k virtualized rows with sortable headers, row selection, column resize and reorder.', implemented: false),
  CatalogEntry(key: 'motion/table-editable', category: 'motion', slug: 'table-editable', name: 'Editable Table', description: 'Edit cells inline and insert or delete rows and columns via border handles; the table re-renders from the updated data and column defs.', implemented: false),
  CatalogEntry(key: 'motion/table-async', category: 'motion', slug: 'table-async', name: 'Async Table', description: 'Loads pages on demand — skeleton rows on first load, then infinite scroll via onEndReached as the virtualized list nears the bottom.', implemented: false),
  CatalogEntry(key: 'motion/bouncy-accordion', category: 'motion', slug: 'bouncy-accordion', name: 'Bouncy Accordion', description: '', implemented: false),
  CatalogEntry(key: 'motion/tilt-card', category: 'motion', slug: 'tilt-card', name: 'Tilt Card', description: '', implemented: false),
  CatalogEntry(key: 'motion/marquee', category: 'motion', slug: 'marquee', name: 'Marquee', description: '', implemented: false),
  CatalogEntry(key: 'motion/text-animation', category: 'motion', slug: 'text-animation', name: 'Text Animation', description: '', implemented: false),
  CatalogEntry(key: 'motion/text-scramble', category: 'motion', slug: 'text-scramble', name: 'Text Scramble', description: 'A controlled character scramble that resolves changed text while keeping its final value accessible.', implemented: false),
  CatalogEntry(key: 'motion/text-shimmer', category: 'motion', slug: 'text-shimmer', name: 'Text Shimmer', description: 'Gradient sweep across text for loading or emphasis.', implemented: false),
  CatalogEntry(key: 'motion/chromatic-text-reveal', category: 'motion', slug: 'chromatic-text-reveal', name: 'Dia Text Animation', description: 'A Dia-inspired text effect with a fixed sentence prefix and a cycling final word revealed by a colorful sweep.', implemented: false),
  CatalogEntry(key: 'motion/number', category: 'motion', slug: 'number', name: 'Number', description: '', implemented: false),
  CatalogEntry(key: 'motion/animated-number', category: 'motion', slug: 'animated-number', name: 'Animated Number', description: 'Spring-driven count-up triggered when in view.', implemented: false),
  CatalogEntry(key: 'motion/number-ticker', category: 'motion', slug: 'number-ticker', name: 'Number Ticker', description: 'Slot-machine rolling digits with staggered entry.', implemented: false),
  CatalogEntry(key: 'motion/animated-badge', category: 'motion', slug: 'animated-badge', name: 'Animated Badge', description: '', implemented: false),
  CatalogEntry(key: 'motion/animated-toast-stack', category: 'motion', slug: 'animated-toast-stack', name: 'Animated Toast Stack', description: '', implemented: false),
  CatalogEntry(key: 'motion/action-swap', category: 'motion', slug: 'action-swap', name: 'Action Swap', description: '', implemented: false),
  CatalogEntry(key: 'motion/action-swap-blur', category: 'motion', slug: 'action-swap-blur', name: 'Blur', description: 'Copy-button style swap with blur, opacity and scale.', implemented: false),
  CatalogEntry(key: 'motion/action-swap-roll', category: 'motion', slug: 'action-swap-roll', name: 'Roll', description: 'The next text or icon rolls in from below with blur.', implemented: false),
  CatalogEntry(key: 'motion/action-swap-cascade', category: 'motion', slug: 'action-swap-cascade', name: 'Cascade', description: 'Letter-by-letter slot roll — the old label\'s letters drop away as the new ones land, left to right.', implemented: false),
  CatalogEntry(key: 'motion/bottom-sheet', category: 'motion', slug: 'bottom-sheet', name: 'Bottom Sheet', description: '', implemented: false),
  CatalogEntry(key: 'motion/pull-to-refresh', category: 'motion', slug: 'pull-to-refresh', name: 'Pull To Refresh', description: '', implemented: false),
  CatalogEntry(key: 'motion/tabs', category: 'motion', slug: 'tabs', name: 'Tabs', description: '', implemented: true),
  CatalogEntry(key: 'motion/switch', category: 'motion', slug: 'switch', name: 'Switch', description: '', implemented: true),
  CatalogEntry(key: 'motion/input', category: 'motion', slug: 'input', name: 'Input', description: '', implemented: true),
  CatalogEntry(key: 'motion/select', category: 'motion', slug: 'select', name: 'Select', description: 'Composable primitives (Select, SelectTrigger, SelectValue, SelectContent, SelectItem); the panel pinches off the trigger and separates, with staggered items. Position-aware (opens upward when needed).', implemented: false),
  CatalogEntry(key: 'motion/select-morph', category: 'motion', slug: 'select-morph', name: 'Morph Select', description: 'Composable primitives (MorphSelect, MorphSelectTrigger, MorphSelectValue, MorphSelectContent, MorphSelectItem) where the trigger morphs into the panel via a shared layoutId — one continuous surface that grows open and shrinks back, never detaching.', implemented: false),
  CatalogEntry(key: 'motion/combobox', category: 'motion', slug: 'combobox', name: 'Combobox', description: '', implemented: false),
  CatalogEntry(key: 'motion/checkbox', category: 'motion', slug: 'checkbox', name: 'Checkbox', description: '', implemented: true),
  CatalogEntry(key: 'motion/radio', category: 'motion', slug: 'radio', name: 'Radio', description: '', implemented: true),
  CatalogEntry(key: 'blocks/otp-input', category: 'blocks', slug: 'otp-input', name: 'Otp Input', description: '', implemented: false),
  CatalogEntry(key: 'blocks/signup-form', category: 'blocks', slug: 'signup-form', name: 'Signup Form', description: '', implemented: false),
  CatalogEntry(key: 'blocks/not-found-glitch', category: 'blocks', slug: 'not-found-glitch', name: 'Glitch', description: 'Digits scramble through random glyphs before resolving, with a chromatic split on hover.', implemented: false),
  CatalogEntry(key: 'blocks/not-found-magnetic', category: 'blocks', slug: 'not-found-magnetic', name: 'Magnetic', description: 'Each digit is cursor-attracted via the Magnetic wrapper and springs back on leave.', implemented: false),
  CatalogEntry(key: 'blocks/not-found-spotlight', category: 'blocks', slug: 'not-found-spotlight', name: 'Spotlight', description: 'A dark panel where a cursor-tracked spotlight reveals the bright code from a dim base.', implemented: false),
  CatalogEntry(key: 'blocks/not-found-stacked', category: 'blocks', slug: 'not-found-stacked', name: 'Stacked', description: 'A code card over a hidden stack that fans out with a spring on hover.', implemented: false),
  CatalogEntry(key: 'blocks/not-found-terminal', category: 'blocks', slug: 'not-found-terminal', name: 'Terminal', description: 'A terminal window that types a failed cd command and a 404 status, with a blinking caret.', implemented: false),
  CatalogEntry(key: 'motion/drawer', category: 'motion', slug: 'drawer', name: 'Drawer', description: '', implemented: false),
  CatalogEntry(key: 'motion/shared-layout-bg', category: 'motion', slug: 'shared-layout-bg', name: 'Shared Layout Bg', description: '', implemented: false),
  CatalogEntry(key: 'motion/bounce-sidebar', category: 'motion', slug: 'bounce-sidebar', name: 'Bounce Sidebar', description: '', implemented: false),
  CatalogEntry(key: 'motion/animated-sidebar', category: 'motion', slug: 'animated-sidebar', name: 'Animated Sidebar', description: '', implemented: false),
  CatalogEntry(key: 'motion/preview-rail', category: 'motion', slug: 'preview-rail', name: 'Preview Rail', description: '', implemented: false),
  CatalogEntry(key: 'motion/dock', category: 'motion', slug: 'dock', name: 'Dock', description: '', implemented: false),
  CatalogEntry(key: 'motion/tooltip', category: 'motion', slug: 'tooltip', name: 'Tooltip', description: '', implemented: false),
  CatalogEntry(key: 'motion/context-menu', category: 'motion', slug: 'context-menu', name: 'Context Menu', description: '', implemented: false),
  CatalogEntry(key: 'motion/popover', category: 'motion', slug: 'popover', name: 'Gooey Popover', description: 'Composable Popover, PopoverTrigger, PopoverContent; the panel oozes out of the trigger through an SVG goo filter with a liquid neck, crisp content fading in on top. Click or hover, controlled or uncontrolled.', implemented: false),
  CatalogEntry(key: 'motion/popover-morph', category: 'motion', slug: 'popover-morph', name: 'Morph Popover', description: 'Composable MorphPopover, MorphPopoverTrigger, MorphPopoverContent; the panel is laid out full size but clipped to the corner nearest the trigger, then unclips as one piece — a single-surface morph with a drop-shadow that hugs the shape. Side/align aware, controlled or uncontrolled.', implemented: false),
  CatalogEntry(key: 'motion/morphing-modal', category: 'motion', slug: 'morphing-modal', name: 'Morphing Modal', description: '', implemented: false),
  CatalogEntry(key: 'motion/center-morph-modal', category: 'motion', slug: 'center-morph-modal', name: 'Center Morph Modal', description: '', implemented: false),
  CatalogEntry(key: 'motion/text-reveal', category: 'motion', slug: 'text-reveal', name: 'Text Reveal', description: 'Word or character reveal with spring slide-up and blur.', implemented: false),
  CatalogEntry(key: 'motion/text-cascade', category: 'motion', slug: 'text-cascade', name: 'Text Cascade', description: 'Letter-by-letter slot roll for standalone text — old letters drop away as new ones land, left to right.', implemented: false),
  CatalogEntry(key: 'motion/button', category: 'motion', slug: 'button', name: 'Button', description: '', implemented: true),
  CatalogEntry(key: 'motion/button-base', category: 'motion', slug: 'button-base', name: 'Button', description: 'Press scale, hover lift, variants and sizes.', implemented: true),
  CatalogEntry(key: 'motion/button-stateful', category: 'motion', slug: 'button-stateful', name: 'Stateful Button', description: 'Idle → loading → success / error with blur-swap slots and morphing width.', implemented: true),
  CatalogEntry(key: 'motion/button-magnetic', category: 'motion', slug: 'button-magnetic', name: 'Magnetic Button', description: 'Button composed with the Magnetic wrapper for cursor-attracted pull.', implemented: true),
  CatalogEntry(key: 'motion/button-metallic', category: 'motion', slug: 'button-metallic', name: 'Metallic Button', description: 'A neutral button surface framed by a pronounced chrome rim with a straight traveling reflection.', implemented: true),
  CatalogEntry(key: 'motion/expandable-control', category: 'motion', slug: 'expandable-control', name: 'Expandable Control', description: '', implemented: false),
  CatalogEntry(key: 'motion/expanding-arrow-button', category: 'motion', slug: 'expanding-arrow-button', name: 'Expanding Arrow Button', description: 'An accent tile that expands into a dotted-arrow trail on hover or focus.', implemented: false),
  CatalogEntry(key: 'motion/hold-action-button', category: 'motion', slug: 'hold-action-button', name: 'Hold Action Button', description: 'Hold to complete with a vertical or horizontal liquid fill; release early to cancel.', implemented: false),
  CatalogEntry(key: 'motion/slide-action-button', category: 'motion', slug: 'slide-action-button', name: 'Slide Action Button', description: 'Drag the thumb to the end to confirm an action; release early to spring back.', implemented: false),
  CatalogEntry(key: 'motion/theme-toggle', category: 'motion', slug: 'theme-toggle', name: 'Theme Toggle', description: '', implemented: false),
  CatalogEntry(key: 'motion/smooth-scroll', category: 'motion', slug: 'smooth-scroll', name: 'Smooth Scroll', description: 'Smooth-scroll provider over Lenis with a useSmoothScroll hook exposing scroll offset, progress and velocity. Reduced-motion safe.', implemented: false),
  CatalogEntry(key: 'motion/scroll-progress', category: 'motion', slug: 'scroll-progress', name: 'Scroll Progress', description: 'Reading-progress indicator — fixed bar or circular ring — driven by scroll position via useSmoothScroll, with spring smoothing.', implemented: false),
  CatalogEntry(key: 'motion/parallax', category: 'motion', slug: 'parallax', name: 'Parallax', description: 'Wrapper that drifts its children at a speed factor as they cross the viewport, on either axis. Reduced-motion safe.', implemented: false),
  CatalogEntry(key: 'motion/scroll-to', category: 'motion', slug: 'scroll-to', name: 'Scroll To', description: 'Button that smooth-scrolls to a target (offset, selector or element) via the active SmoothScroll provider; reduced-motion jumps instantly.', implemented: false),
  CatalogEntry(key: 'motion/scroll-reveal', category: 'motion', slug: 'scroll-reveal', name: 'Scroll Reveal', description: 'Reveals its children with a spring slide and blur as they enter the viewport, once or every time. Reduced-motion keeps a fade.', implemented: false),
  CatalogEntry(key: 'motion/range-slider', category: 'motion', slug: 'range-slider', name: 'Range Slider', description: 'Tick dots, and a vertical-bar thumb that bounces as it lands on each step.', implemented: false),
  CatalogEntry(key: 'motion/range-slider-fluid', category: 'motion', slug: 'range-slider-fluid', name: 'Fluid Slider', description: 'No thumb. The fill slides behind a rounded liquid cap, and the label flips color wherever the fill covers it.', implemented: false),
  CatalogEntry(key: 'motion/range-slider-wave', category: 'motion', slug: 'range-slider-wave', name: 'Wave Slider', description: 'Equalizer bars peak around the handle and drop back once it passes, so the value moves down the track as a wave.', implemented: false),
  CatalogEntry(key: 'motion/range-slider-bubble', category: 'motion', slug: 'range-slider-bubble', name: 'Bubble Slider', description: 'Grab the thumb and a value bubble pops out of it. The bubble tilts and squashes with how fast you drag, then settles upright.', implemented: false),
  CatalogEntry(key: 'motion/range-slider-ruler', category: 'motion', slug: 'range-slider-ruler', name: 'Ruler Slider', description: 'The needle stays put and the scale scrolls under it. A flick keeps going and settles on the nearest tick. Fractional steps read at the step\'s own precision.', implemented: false),
  CatalogEntry(key: 'motion/wheel-picker', category: 'motion', slug: 'wheel-picker', name: 'Wheel Picker', description: '', implemented: false),
  CatalogEntry(key: 'motion/shader-background', category: 'motion', slug: 'shader-background', name: 'Shader Background', description: '', implemented: false),
  CatalogEntry(key: 'motion/cylinder-carousel', category: 'motion', slug: 'cylinder-carousel', name: 'Cylinder Carousel', description: '', implemented: false),
  CatalogEntry(key: 'motion/loader', category: 'motion', slug: 'loader', name: 'Loader', description: '', implemented: false),
];

List<CatalogEntry> catalogFor(String category, {bool liveOnly = true}) {
  final items = catalog.where((e) => e.category == category).toList();
  if (liveOnly) return items.where((e) => e.implemented).toList();
  return items;
}

class CatalogCopy {
  const CatalogCopy({
    required this.heading,
    required this.description,
  });
  final String heading;
  final String description;
}

const categoryCopy = <String, CatalogCopy>{
  'motion': CatalogCopy(
    heading: 'Animated Flutter components',
    description:
        'Explore animated Flutter widgets ported from beUI. Same springs, same interaction contracts, copy the Dart source into your app.',
  ),
  'blocks': CatalogCopy(
    heading: 'Animated Flutter UI blocks',
    description:
        'Product-ready animated blocks. Copy complete interactions into your app and adapt the source to your product.',
  ),
  'agents': CatalogCopy(
    heading: 'Animated AI agent components',
    description:
        'Build clear, responsive AI experiences with components for agent reasoning, progress, tool activity, and conversation states.',
  ),
};

class CatalogGroup {
  const CatalogGroup({
    required this.title,
    required this.description,
    required this.slugs,
  });
  final String title;
  final String description;
  final List<String> slugs;
}

const agentGroups = <CatalogGroup>[
  CatalogGroup(
    title: 'Conversation components',
    description:
        'Compose prompts, arrange sender-aware messages, shape conversational surfaces, and keep streamed turns stable while the reader moves through the transcript.',
    slugs: ['prompt-input', 'message', 'message-bubble', 'message-scroller'],
  ),
  CatalogGroup(
    title: 'Response and evidence components',
    description:
        'Render rich answers as they arrive, reveal completion actions at the right time, and connect generated claims to inspectable sources.',
    slugs: ['streaming-response', 'image-generation', 'citations'],
  ),
  CatalogGroup(
    title: 'Progress and planning components',
    description:
        'Communicate unknown waits, durable task plans, and chronological agent activity without inventing precision or exposing an unfiltered trace.',
    slugs: ['thinking-shimmer', 'agent-progress', 'reasoning-text', 'todo-list', 'agent-activity'],
  ),
  CatalogGroup(
    title: 'Tool and code components',
    description:
        'Present execution outcomes, generated source, and file changes with bounded streaming, stable highlighting, and inspectable completion states.',
    slugs: ['tool-result', 'code-block', 'file-diff'],
  ),
  CatalogGroup(
    title: 'Human-in-the-loop components',
    description:
        'Pause agent work for a scoped permission, clarification, review, or decision, then preserve the resolved outcome in the run history.',
    slugs: ['tool-approval', 'approval-card'],
  ),
];

