#!/usr/bin/env bun
/** Dump React preview keys + registry names into apps/gallery/lib/catalog/catalog.dart */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const react = join(here, "../../ui-components");
const dest = join(here, "../apps/gallery/lib/catalog/catalog.dart");

const previews = readFileSync(join(react, "components/previews/index.tsx"), "utf8");
const registry = readFileSync(join(react, "lib/registry.ts"), "utf8");

const keys = [...previews.matchAll(/"((?:motion|agents|blocks)\/[^"]+)"\s*:/g)].map(
  (m) => m[1],
);

const names = new Map();
let pendingName = "";
for (const line of registry.split("\n")) {
  const name = line.match(/name:\s+"([^"]+)"/);
  if (name) pendingName = name[1];
  const preview = line.match(/previewKey:\s+"([^"]+)"/);
  if (preview && pendingName) names.set(preview[1], pendingName);
  const install = line.match(/installSlug:\s+"([^"]+)"/);
  if (install && pendingName) names.set(install[1], pendingName);
}

const implemented = new Set([
  "motion/button",
  "motion/button-base",
  "motion/button-stateful",
  "motion/button-magnetic",
  "motion/button-metallic",
  "motion/switch",
  "motion/checkbox",
  "motion/radio",
  "motion/input",
  "motion/tabs",
]);

const title = (key) => {
  if (names.has(key)) return names.get(key);
  const slug = key.split("/")[1];
  if (names.has(slug)) return names.get(slug);
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
};

const entries = keys.map((key) => {
  const [category, ...rest] = key.split("/");
  const slug = rest.join("/");
  return {
    key,
    category,
    slug,
    name: title(key),
    implemented: implemented.has(key),
  };
});

const dart = `// Generated by tools/export-catalog.mjs — do not edit by hand.
class CatalogEntry {
  const CatalogEntry({
    required this.key,
    required this.category,
    required this.slug,
    required this.name,
    required this.implemented,
  });

  final String key;
  final String category;
  final String slug;
  final String name;
  final bool implemented;

  String get reactUrl =>
      'https://beui.dev/components/\$category/\${slug.contains('-') && category == 'motion' ? slug.split('-').first : slug}';
}

const catalog = <CatalogEntry>[
${entries
  .map(
    (e) =>
      `  CatalogEntry(key: '${e.key}', category: '${e.category}', slug: '${e.slug}', name: '${e.name.replace(/'/g, "\\'")}', implemented: ${e.implemented}),`,
  )
  .join("\n")}
];

List<CatalogEntry> catalogFor(String category) =>
    catalog.where((e) => e.category == category).toList();
`;

writeFileSync(dest, dart);
console.log(`wrote ${entries.length} entries (${[...implemented].length} implemented) → ${dest}`);
